- name: ZendeskGleanWebhookFunction
  description: Lambda function to process Zendesk webhooks and send them to Glean
  build:
    provider: dkcicd
    pipelines:
    - name: lambda-build-v1
      parameters:
        projectPath: Zendesk-Glean-Answers
        awsAccountId: '053131491888'
        awsRegion: us-east-1
        runtimeVersion: 3.10-bullseye
        command: install
        projectName: ZendeskGleanWebhookFunction
        pulumiProjectPath: .vtex/infrastructure/lambda/ZendeskGleanWebhookFunction
        s3BucketName: glean-zendesk-integration
        versionTag: '{{ ref_name }}'
        packageManager: pip
      when:
      - event: push
        source: tag
        regex: ^v(\d+)\.(\d+)\.(\d+)$

    - name: dk-iac-preview-infra-v1
      parameters:
        projectName: techops/zendesk-glean-lambda
        stackName: vtex/dev
        projectPath: .vtex/infrastructure/lambda/ZendeskGleanWebhookFunction                           
        awsAccountId: '053131491888'
        awsRegion: us-east-1
      runtime:
        serviceAccountName: dk-cicd-iac
      when:
        - event: push
          path:
            - .vtex/infrastructure/
          source: branch
          regex: ^(?!main$).*

    - name: dk-iac-deploy-infra-v1
      parameters:
        projectName: techops/zendesk-glean-lambda
        stackName: vtex/dev
        projectPath: .vtex/infrastructure/lambda/ZendeskGleanWebhookFunction                           
        awsAccountId: '053131491888'
        awsRegion: us-east-1
      runtime:
        serviceAccountName: dk-cicd-iac
      when:
        - event: push
          path:
            - .vtex/infrastructure/ZendeskGleanWebhookFunction
          source: branch
          regex: ^(main)$
      
