- name: ZendeskGleanWebhookFunction
  description: Lambda function to process Zendesk webhooks and send them to Glean
  build:
    provider: dkcicd
    pipelines:
    - name: lambda-build-v1
      parameters:
        projectPath: Zendesk - Glean -Answers\lambda_zendesk_glean.py
        awsAccountId: '558830342743'
        awsRegion: us-east-1
        rentimeVersion: 3.10-bullseye
        command: install
        projectName: techops/zendesk-glean-lambda
        pulumiProjectPath: ".vtex/infrastructure/lambda/ZendeskGleanWebhookFunction"
        s3BucketName: glean-zendesk-integration
        versionTag: '{{ ref_name }}'

      when:
      - event: push
        source: branch
      runtime:
        serviceAccountName: dk-cicd-iac        