- name: ZendeskGleanWebhookFunction
  description: Lambda function to process Zendesk webhooks and send them to Glean
  build:
    provider: dkcicd
    pipelines:
      - name: lambda-build-v1
        parameters:
          pulumiProjectPath: ".vtex/infrastructure/ZendeskGleanWebhookFunction"
          awsAccountId: '053131491888'
          projectPath: CardTokenVault.Lambda.Import
          projectName: techops/zendesk-glean-lambda
          s3BucketName: glean-zendesk-integration
          versionTag: '{{ ref_name }}'
          runtimeVersion: 8.0--alpine
          packageManager: yarn
          command: publish
        when:
          - event: push
            source: tag
            regex: .*

      - name: dk-iac-deploy-infra-v1
        parameters:
          projectName: techops/zendesk-glean-lambda
          stackName: vtex/dev
          projectPath: ".vtex/infrastructure/lambda/ZendeskGleanWebhookFunction"                           
          awsAccountId: '558830342743'
          awsRegion: us-east-1
          awsRoleName: dk-cicd-558830342743
        when:
          - event: push
            path:
              - .vtex/infrastructure/**
            source: branch
            regex: ^(main)$

      - name: dk-iac-preview-infra-v1
        parameters:
          projectName: techops/zendesk-glean-lambda
          stackName: vtex/dev
          projectPath: ".vtex/infrastructure/lambda/ZendeskGleanWebhookFunction"                           
          awsAccountId: '558830342743'
          awsRegion: us-east-1
          awsRoleName: dk-cicd-558830342743
        when:
          - event: push
            path:
              - .vtex/infrastructure/**
            source: branch