- name: ZendeskGleanWebhookFunction
  description: Lambda function to process Zendesk webhooks and send them to Glean
  build:
    provider: dkcicd
    pipelines:
      - name: dk-iac-deploy-infra-v1
        parameters:
          gitRepositoryName: glean  
          gitRepositoryOwner: vtex                      
          gitBranchName: main                           
          projectName: techops/zendesk-glean-lambda     
          stackName: dev                                
          projectPath: .vtex/infrastructure/lambda                           
          awsAccountId: 558830342743                  
          awsRegion: us-east-1
          awsRoleName: dk-iac-558830342743              
        when:
          - event: push
            source: branch
