name: ZendeskGleanWebhookFunction
runtime: yaml
description: ""
outputs:
  id: ""
resources:
  lambda:
    type: ""
    properties:
      name: ""
      handler: ""
      runtime: ""
      s3Bucket: ""
      s3Key: glean/ZendeskGleanWebhookFunction/v1.0.14-ZendeskGleanWebhookFunction.zip
      memorySize: 0
      ephemeralStorageSize: 0
      timeout: 0
